name: Deploy to GitHub Pages
on: push
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4

      - name: Update theme
        run: git submodule update --init --recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.121.1"

      - name: Build
        run: hugo --gc --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./public
          cname: leins275.xyz
          publish_branch: main

